config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'
  resources :vendors, only: [:new, :create, :show, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/vendor.rb
class Vendor < ApplicationRecord
  validates :company_name, presence: true
  validates :address, presence: true
  validates :phone, presence: true
  validates :contact_name, presence: true
  validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController
  before_action :authenticate_user!, only: [:new]

  def new
    @vendor = Vendor.new
  end

  def create
    @vendor = Vendor.new(set_params)
    if @vendor.save
      redirect_to @vendor
    else
      flash.now[:alert] = 'Não é possível cadastrar fornecedor'
      render :new
    end
  end

  def show
    @vendor = Vendor.find(params[:id])
  end

  def edit
    @vendor = Vendor.find(params[:id])
  end

  def update
    @vendor = Vendor.find(params[:id])
    if @vendor.update(set_params)
      redirect_to @vendor
    else
      flash.now[:alert] = 'Não é possível atualizar fornecedor'
      render :edit
    end
  end

  private

  def set_params
    params.require(:vendor).permit(:company_name, :address,
                                   :phone, :contact_name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<h1>Welcome</h1>
<% if user_signed_in? %>
  <p>
    <strong>Bem vindo <%= current_user.email %></strong>
    <%= link_to 'Novo Fornecedor', new_vendor_path %>
  </p>
<% else %>
  <%= link_to 'Entrar', new_user_session_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WcVendors</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/vendors/_vendor.html.erb
<%= simple_form_for @vendor do |f| %>
  <%= f.input :company_name, label: 'Razão Social' %>
  <%= f.input :address, label: 'Endereço' %>
  <%= f.input :phone, label: 'Telefone' %>
  <%= f.input :contact_name, label: 'Contato' %>
  <%= f.input :email, label: 'Email' %>
  <% if @vendor.id.blank? %>
    <%= f.submit 'Registrar' %>
  <% else %>
    <%= f.submit 'Atualizar' %>
  <% end %>
<% end %>

<%= link_to 'Voltar', root_path %>
<% flash.each do |name, msg| -%>
  <%= content_tag :div, msg, class: name %>
<% end %>

app/views/vendors/edit.html.erb
<%= render partial: @vendor %>

app/views/vendors/new.html.erb
<%= simple_form_for @vendor do |f| %>
  <%= f.input :company_name, label: 'Razão Social' %>
  <%= f.input :address, label: 'Endereço' %>
  <%= f.input :phone, label: 'Telefone' %>
  <%= f.input :contact_name, label: 'Contato' %>
  <%= f.input :email, label: 'Email' %>
  <%= f.submit 'Registrar' %>
<% end %>

<% flash.each do |name, msg| -%>
  <%= content_tag :div, msg, class: name %>
<% end %>

app/views/vendors/show.html.erb
<p>Razão Social: <%= @vendor.company_name %></p>
<p>Endereço: <%= @vendor.address %></p>
<p>Telefone: <%= @vendor.phone %></p>
<p>Contato: <%= @vendor.contact_name %></p>
<p>Email: <%= @vendor.email %></p>
<%= link_to 'Voltar', root_path %>